### ISSUE TITLE
Add pi 4 versions

### ISSUE THREAD

**Issue by christophehurpeau** [jcane86/raspi-ver#10]
Hello ! Theses versions are missing:

- a03111 for the 1G
- b03111 for the 2G
- c03111 for the 4G

I didn't create a PR because I don't know what to write for `PCBRev` and `notes`
Thanks :)

**Comment by jcane86** [comment]
Hi Crhistophe, sorry for the delay.

The info is based off of the info found here: https://elinux.org/RPi_HardwareHistory#Board_Revision_History

you can take that as an example if you want and send a PR this way!

Cheers!

Pepe
