### ISSUE TITLE
missing a020d3 inversions.jsons

### ISSUE THREAD

**Issue by jalaman23** [jcane86/raspi-ver#2]
hi,
it is possible that 
"a020d3": {
      "relDate": "Q1 2018",
      "model": "3 model B+",
      "PCBRev": "1.3",
      "memory": "1 GB",
      "notes": "(Mfg by Sony)"
   },
is missing in the version.json file?

Thank you for your answer

**Comment by jcane86** [comment]
Yep, totally right, that's a new one.
Feel free to open a pull request adding that, or I can try to do it later. 

Cheers

Pepe

**Comment by jalaman23** [comment]
so i make my first pull request :) 
I hope everything is right.

**Comment by jcane86** [comment]
Closed in #3
